name: Build pkgs
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'just for fun hit enter'
        required: false
        default: ""
  
jobs:
  buildpkg:
    runs-on: ubuntu-22.04
    container:
      image: termux/termux-docker:latest
    steps:

      - name: Install Required Packages
        run: |
          apt update
          apt install neofetch -y
          neofetch
  
