name: Build pkgs
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'just for fun hit enter'
        required: true
        default: ""
  
jobs:
  buildpkg:
    runs-on: ubuntu-22.04
    container:
      image: termux/termux-docker:latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install flex -y
          apt-get install neofetch -y
          neofetch
  
