name: Build pkgs
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'hit enter'
        required: false
        default: ""

jobs:
  buildpkg:
    runs-on: ubuntu-22.04
    steps:
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Satify Dependencies
      run: sudo apt-get update; sudo apt-get install git build-essential binfmt-support qemu-user-static debootstrap -y
 
    - name: Install env
      run: |
         sudo apt install proot 2to3 python2-minimal python2 dh-python python-is-python3 wget -y
         mkdir -p .github/scripts/
         wget https://github.com/Ash-ketchm/termux-hw-accel/raw/main/.github/scripts/termux-install64 -P .github/scripts/termux-ch64
         wget https://github.com/Ash-ketchm/termux-hw-accel/raw/main/.github/scripts/termux-chroot64 -P .github/scripts/termux-64
         cp .github/scripts/termux-ch64 /usr/bin/
         cp .github/scripts/termux-64 /usr/bin
         chmod 777 /usr/bin/termux*
         termux-ch64
         termux-64
         apt update
         apt install neofetch
         neofetch
